services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wp_files:/var/www/html
    restart: always


  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - wp_files:/var/www/html
    restart: always


  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - wp_database:/var/lib/mysql
    restart: always

volumes:
  wp_database:
    driver: local
    driver_opts:
      device: /home/aloubry/data/wp_database
      type: none
      o: bind
  wp_files:
    driver: local
    driver_opts:
      device: /home/aloubry/data/wp_files
      type: none
      o: bind

networks:
  inception_network:
    driver: bridge