version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - /home/aloubry/data/wp_files:/var/www/html
    restart: always


  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - /home/aloubry/data/wp_files:/var/www/html
    restart: always


  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - /home/aloubry/data/wp_database:/var/lib/mysql
    restart: always


networks:
  inception_network:
    driver: bridge